language: python

python:
    - 2.7

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install python-dev python-libvirt libffi-dev libssl-dev
  - sudo apt-get install libxml2-dev libxslt1-dev libjpeg-dev
  - sudo apt-get install libpq-dev mysql-server libmysqlclient-dev

  # Setup the various databases.
  - sudo mysql -e "CREATE USER cuckoo@localhost IDENTIFIED BY 'cuckoo'"
  - sudo mysql -e "GRANT ALL PRIVILEGES ON * . * TO cuckoo@localhost"
  - sudo mysql -e "FLUSH PRIVILEGES"
  - sudo mysql -e "CREATE DATABASE cuckootest"
  - sudo -u postgres psql -c "CREATE USER cuckoo WITH PASSWORD 'cuckoo'"
  - sudo -u postgres psql -c "CREATE DATABASE cuckootest"

install:
  - ONLYINSTALL=yes python setup.py develop
  - pip install psycopg2 mysql-python
  - pip install pytest pytest-cov coveralls

script:
  # Create the Cuckoo Working Directory.
  - cuckoo -d

  # Download Cuckoo Signatures.
  - cuckoo community

  # Check the code integrity of the Signatures by running Cuckoo.
  - cuckoo -d 2>&1|grep "Unable to bind ResultServer"

  # Run tests from the "tests" directory.
  - py.test --cov=cuckoo

after_success:
  - coveralls
