language:
- objective-c # make it run on OS X workers *only*
install:
    - brew install python
    - brew link --overwrite python
    - sudo easy_install pymongo
    - pip install nose
script:
    - nosetests ./tests/test_dtruss.py
    - nosetests ./tests/test_apicalls.py
    - nosetests ./tests/test_ipconnections.py
    - nosetests ./tests/test_analyzer.py
