language:
- objective-c # make it run on OS X workers *only*
notifications:
  email:
    on_success: never
    on_failure: always
install:
    - brew install python
    - brew link --overwrite python
    - pip install -r requirements-dev.txt
script:
    - nosetests ./tests/test_dtruss.py
    - nosetests ./tests/test_apicalls.py
    - nosetests ./tests/test_ipconnections.py
    - nosetests ./tests/test_analyzer.py
    - nosetests ./tests/test_packages.py
