branches:
  only:
    - package

language: python

python:
    - 2.7

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install python-dev python-libvirt libffi-dev libssl-dev
    - sudo apt-get install libxml2-dev libxslt1-dev libjpeg-dev

install:
    - ONLYINSTALL=yes python setup.py install

script:
    # Create the Cuckoo Working Directory.
    - cuckoo -d

    # Download Cuckoo Signatures.
    - cuckoo community

    # Check the code integrity of the Signatures by running Cuckoo.
    - cuckoo -d 2>&1|grep "Unable to bind ResultServer"

    # Run tests from the "tests" directory.
    - py.test
